### ISSUE TITLE
Add containers Health Check

### ISSUE THREAD

**Issue by lerignoux** [lerignoux/family-ai#9]
Better add health check to the project containers

for ref:
```
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:3000"]
  interval: 30s
  timeout: 5s
  retries: 1
```
